### ISSUE TITLE
AUR - fuzzylite compilation failed

### ISSUE THREAD

**Issue by tom-i** [fuzzylite/fuzzylite#110]
Hi,
I have Archlinux and there is vcmi-git which has dependancy `fuzzylite`.
Unfortunatelly it crash with this stack:

```
==> Checking buildtime dependencies...
==> WARNING: Using existing $srcdir/ tree
==> Starting build()...
-- The CXX compiler identification is GNU 12.2.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done

=====================================
fuzzylite v6.0

FL_CPP98=OFF
FL_USE_FLOAT=OFF
FL_BACKTRACE=ON
FL_LIBS=
FL_INSTALL_BINDIR=bin
FL_INSTALL_LIBDIR=lib
FL_BUILD_TESTS=OFF

CMAKE_BUILD_TYPE=None
CMAKE_CXX_COMPILER_ID=GNU
CMAKE_CXX_COMPILER_VERSION=12.2.0
CMAKE_CXX_FLAGS=-pedantic -Wall -Wextra -Werror -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection -Wp,-D_GLIBCXX_ASSERTIONS
CMAKE_OSX_DEPLOYMENT_TARGET=
COMPILE_DEFINITIONS:
-- Defined: FL_BUILD_PATH="/home/tomasi/.cache/yay/fuzzylite/src/fuzzylite-6.0/fuzzylite"
-- Defined: FL_BACKTRACE
=====================================

-- Configuring done
-- Generating done
-- Build files have been written to: /home/tomasi/.cache/yay/fuzzylite/src/build
make: Entering directory '/home/tomasi/.cache/yay/fuzzylite/src/build'
make[1]: Entering directory '/home/tomasi/.cache/yay/fuzzylite/src/build'
make[2]: Entering directory '/home/tomasi/.cache/yay/fuzzylite/src/build'
make[2]: Leaving directory '/home/tomasi/.cache/yay/fuzzylite/src/build'
make[2]: Entering directory '/home/tomasi/.cache/yay/fuzzylite/src/build'
[  1%] Building CXX object CMakeFiles/fl-obj.dir/src/Benchmark.cpp.o
[  2%] Building CXX object CMakeFiles/fl-obj.dir/src/Complexity.cpp.o
[  3%] Building CXX object CMakeFiles/fl-obj.dir/src/Console.cpp.o
[  4%] Building CXX object CMakeFiles/fl-obj.dir/src/activation/First.cpp.o
[  5%] Building CXX object CMakeFiles/fl-obj.dir/src/activation/General.cpp.o
[  6%] Building CXX object CMakeFiles/fl-obj.dir/src/activation/Highest.cpp.o
[  7%] Building CXX object CMakeFiles/fl-obj.dir/src/activation/Last.cpp.o
[  8%] Building CXX object CMakeFiles/fl-obj.dir/src/activation/Lowest.cpp.o
[  9%] Building CXX object CMakeFiles/fl-obj.dir/src/activation/Proportional.cpp.o
[ 10%] Building CXX object CMakeFiles/fl-obj.dir/src/activation/Threshold.cpp.o
[ 11%] Building CXX object CMakeFiles/fl-obj.dir/src/defuzzifier/Bisector.cpp.o
[ 12%] Building CXX object CMakeFiles/fl-obj.dir/src/defuzzifier/Centroid.cpp.o
[ 13%] Building CXX object CMakeFiles/fl-obj.dir/src/defuzzifier/IntegralDefuzzifier.cpp.o
[ 14%] Building CXX object CMakeFiles/fl-obj.dir/src/defuzzifier/LargestOfMaximum.cpp.o
[ 15%] Building CXX object CMakeFiles/fl-obj.dir/src/defuzzifier/MeanOfMaximum.cpp.o
[ 16%] Building CXX object CMakeFiles/fl-obj.dir/src/defuzzifier/SmallestOfMaximum.cpp.o
[ 17%] Building CXX object CMakeFiles/fl-obj.dir/src/defuzzifier/WeightedAverage.cpp.o
[ 18%] Building CXX object CMakeFiles/fl-obj.dir/src/defuzzifier/WeightedAverageCustom.cpp.o
[ 19%] Building CXX object CMakeFiles/fl-obj.dir/src/defuzzifier/WeightedDefuzzifier.cpp.o
[ 19%] Building CXX object CMakeFiles/fl-obj.dir/src/defuzzifier/WeightedSum.cpp.o
[ 20%] Building CXX object CMakeFiles/fl-obj.dir/src/defuzzifier/WeightedSumCustom.cpp.o
[ 21%] Building CXX object CMakeFiles/fl-obj.dir/src/Engine.cpp.o
[ 22%] Building CXX object CMakeFiles/fl-obj.dir/src/Exception.cpp.o
[ 23%] Building CXX object CMakeFiles/fl-obj.dir/src/factory/ActivationFactory.cpp.o
[ 24%] Building CXX object CMakeFiles/fl-obj.dir/src/factory/DefuzzifierFactory.cpp.o
[ 25%] Building CXX object CMakeFiles/fl-obj.dir/src/factory/FactoryManager.cpp.o
[ 26%] Building CXX object CMakeFiles/fl-obj.dir/src/factory/FunctionFactory.cpp.o
[ 27%] Building CXX object CMakeFiles/fl-obj.dir/src/factory/HedgeFactory.cpp.o
[ 28%] Building CXX object CMakeFiles/fl-obj.dir/src/factory/SNormFactory.cpp.o
[ 29%] Building CXX object CMakeFiles/fl-obj.dir/src/factory/TermFactory.cpp.o
[ 30%] Building CXX object CMakeFiles/fl-obj.dir/src/factory/TNormFactory.cpp.o
[ 31%] Building CXX object CMakeFiles/fl-obj.dir/src/fuzzylite.cpp.o
[ 32%] Building CXX object CMakeFiles/fl-obj.dir/src/hedge/Any.cpp.o
[ 33%] Building CXX object CMakeFiles/fl-obj.dir/src/hedge/Extremely.cpp.o
[ 34%] Building CXX object CMakeFiles/fl-obj.dir/src/hedge/HedgeFunction.cpp.o
[ 35%] Building CXX object CMakeFiles/fl-obj.dir/src/hedge/Not.cpp.o
[ 36%] Building CXX object CMakeFiles/fl-obj.dir/src/hedge/Seldom.cpp.o
[ 37%] Building CXX object CMakeFiles/fl-obj.dir/src/hedge/Somewhat.cpp.o
[ 38%] Building CXX object CMakeFiles/fl-obj.dir/src/hedge/Very.cpp.o
[ 39%] Building CXX object CMakeFiles/fl-obj.dir/src/imex/CppExporter.cpp.o
[ 39%] Building CXX object CMakeFiles/fl-obj.dir/src/imex/Exporter.cpp.o
[ 40%] Building CXX object CMakeFiles/fl-obj.dir/src/imex/FclExporter.cpp.o
[ 41%] Building CXX object CMakeFiles/fl-obj.dir/src/imex/FclImporter.cpp.o
[ 42%] Building CXX object CMakeFiles/fl-obj.dir/src/imex/FisExporter.cpp.o
[ 43%] Building CXX object CMakeFiles/fl-obj.dir/src/imex/FisImporter.cpp.o
[ 44%] Building CXX object CMakeFiles/fl-obj.dir/src/imex/FldExporter.cpp.o
[ 45%] Building CXX object CMakeFiles/fl-obj.dir/src/imex/FllExporter.cpp.o
[ 46%] Building CXX object CMakeFiles/fl-obj.dir/src/imex/FllImporter.cpp.o
[ 47%] Building CXX object CMakeFiles/fl-obj.dir/src/imex/Importer.cpp.o
[ 48%] Building CXX object CMakeFiles/fl-obj.dir/src/imex/JavaExporter.cpp.o
[ 49%] Building CXX object CMakeFiles/fl-obj.dir/src/imex/RScriptExporter.cpp.o
[ 50%] Building CXX object CMakeFiles/fl-obj.dir/src/main.cpp.o
/home/tomasi/.cache/yay/fuzzylite/src/fuzzylite-6.0/fuzzylite/src/main.cpp: In function ‘int main(int, const char**)’:
/home/tomasi/.cache/yay/fuzzylite/src/fuzzylite-6.0/fuzzylite/src/main.cpp:24:24: error: ‘void (* std::set_unexpected(unexpected_handler))()’ is deprecated [-Werror=deprecated-declarations]
   24 |     std::set_unexpected(fl::Exception::terminate);
      |     ~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/c++/12.2.0/ios:39,
                 from /usr/include/c++/12.2.0/ostream:38,
                 from /usr/include/c++/12.2.0/iostream:39,
                 from /home/tomasi/.cache/yay/fuzzylite/src/fuzzylite-6.0/fuzzylite/./fl/fuzzylite.h:22,
                 from /home/tomasi/.cache/yay/fuzzylite/src/fuzzylite-6.0/fuzzylite/./fl/Headers.h:27,
                 from /home/tomasi/.cache/yay/fuzzylite/src/fuzzylite-6.0/fuzzylite/src/main.cpp:17:
/usr/include/c++/12.2.0/exception:91:22: note: declared here
   91 |   unexpected_handler set_unexpected(unexpected_handler) _GLIBCXX_USE_NOEXCEPT;
      |                      ^~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors
make[2]: *** [CMakeFiles/fl-obj.dir/build.make:790: CMakeFiles/fl-obj.dir/src/main.cpp.o] Error 1
make[2]: Leaving directory '/home/tomasi/.cache/yay/fuzzylite/src/build'
make[1]: *** [CMakeFiles/Makefile2:87: CMakeFiles/fl-obj.dir/all] Error 2
make[1]: Leaving directory '/home/tomasi/.cache/yay/fuzzylite/src/build'
make: *** [Makefile:136: all] Error 2
make: Leaving directory '/home/tomasi/.cache/yay/fuzzylite/src/build'
==> ERROR: A failure occurred in build().
    Aborting...
 -> error making: fuzzylite 
```

**Comment by jcrada** [comment]
This has been resolved in https://github.com/fuzzylite/fuzzylite/issues/94

**Comment by kerneliusz** [comment]
I'm afraid not, @jcrada. I applied the patch from #94 (https://github.com/fuzzylite/fuzzylite/files/7972235/fix-tests.patch.txt) to vanilla fuzzylite 6.0 source code (https://github.com/fuzzylite/fuzzylite/archive/refs/tags/v6.0.tar.gz) and it still fails with the exact same message on gcc 12.

**Comment by jcrada** [comment]
Hi @kerneliusz. Thanks for your comment. At the moment I am busy with pyfuzzylite, but as soon as I release the next version I will come back to fuzzylite. Sorry I cannot address this at the moment.

**Comment by kerneliusz** [comment]
Don't worry. Once I test it, I will share some patches I made.

**Comment by kerneliusz** [comment]
@jcrada I made some patches and they're available here: https://bugs.gentoo.org/905664
However, I am still unable to test any of this because I'm unable to compile VCMI - the only fuzzylite user I know. There's an issue here https://github.com/vcmi/vcmi/issues/2115
Do you know how can I test if the fuzzylite I compiled works as intended?

**Comment by kambala-decapitator** [comment]
I also faced this and was able to workaround by installing `fuzzylite-git` package instead of `fuzzylite`: the former doesn't make the warning be an error
